#!/usr/bin/env python

# Settings schema
SCHEMA = "com.linuxmint.git-monkey"
SCHEMA_TERM = "org.cinnamon.desktop.default-applications.terminal"

# Settings keys
KEY_BUILD = "build-command"
KEY_REPOS = "repos"
KEY_DEV_MODE = "dev-mode"
KEY_TERM = "exec"

# Repo states
STATE_NONE = -1

STATE_BUILDING = 2
STATE_REBASING = 3
STATE_CLEANING = 4
STATE_RESETTING = 5
STATE_NEW_BRANCH_IN_PROGRESS = 6
STATE_PULL_REQUEST_IN_PROGRESS = 7

STATE_NEW_BRANCH_QUEUED = 8
STATE_CLEAN_QUEUED = 9
STATE_RESET_QUEUED = 10
STATE_BUILD_QUEUED = 11
STATE_REBASE_QUEUED = 12
STATE_PULL_REQUEST_QUEUED = 13

STATE_NEW_BRANCH_DONE = 14
STATE_RESETTED = 15
STATE_BUILT = 16
STATE_REBASED = 17
STATE_CLEANED = 18
STATE_PULL_REQUEST_CHECKED_OUT = 19
STATE_ABORTED = 20

# Job states
JOB_BUILD = 1
JOB_REBASE = 2
JOB_RESET = 3
JOB_CLEAN = 4
JOB_NEW_BRANCH = 5
JOB_CHECKOUT_PR = 6
